### ISSUE TITLE
Incorrect version bump

### ISSUE THREAD

**Issue by Grinnz** [powerman/perl-CGI-Easy#1]
The latest version of this distribution is v1.0.1, however the previous version was 1.000001, which evaluates to the same version when following Perl version mapping. In addition, when a vendor packaging dists for RPMs maps to version tuples, the previous version would likely be equivalent to v1.1 in that context. Therefore your next version should ideally be greater than v1.1.0. (It is recommended for these reasons to bump the major version when changing version formats, to keep things simple.)

```
$ perl -E'say version->parse("1.000001") <=> version->parse("v1.0.1")'
0
```

**Comment by powerman** [comment]
Thanks, closed via 92a54d5.
